version: '3.3'

services:
  db:
    image: 'postgres:12-alpine'
    hostname: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rss_db
    ports:
      - '5439:5432'

  redis:
    image: 'redis:6-alpine'
    hostname: redis
    volumes:
      - redis_data:/data/
    ports:
      - '6379'

  web:
    build:
      context: .
    volumes:
      - ./:/app
    ports:
      - 8005:8005
    environment:
      - DEBUG=True
      - SECRET_KEY=some-ramdom-string-here
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/rss_db
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  redis_data:
