# Generated by Django 3.2.3 on 2022-02-11 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedservice', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='feed',
            index=models.Index(fields=['url'], name='feedservice_url_7b71b8_idx'),
        ),
    ]
