# Generated by Django 3.2.3 on 2022-02-11 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedservice', '0002_feed_feedservice_url_7b71b8_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feeditems',
            options={'ordering': ['-created_at']},
        ),
    ]
