# Generated by Django 3.2.3 on 2022-02-12 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedservice', '0004_auto_20220211_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeditems',
            old_name='updated_at',
            new_name='published_at',
        ),
    ]
