# Generated by Django 3.2.3 on 2022-02-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedservice', '0005_rename_updated_at_feeditems_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditems',
            name='entry_id',
            field=models.CharField(default=None, max_length=225, null=True),
        ),
    ]
