# Generated by Django 3.2.3 on 2022-02-12 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedservice', '0006_feeditems_entry_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feeditems',
            options={'ordering': ['published_at']},
        ),
    ]
