# Generated by Django 3.2.3 on 2022-02-14 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedservice', '0007_alter_feeditems_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feeditems',
            options={'ordering': ['-published_at']},
        ),
    ]
